### ISSUE TITLE
How to obtain expert trajectory data

### ISSUE THREAD

**Issue by Lygggggg** [TMmichi/mujoco_jaco#3]
Hello, I would like to ask how the expert trajectory data in the folder models_baselines/trajectories is obtained,thank you!

**Comment by TMmichi** [comment]
Those trajectories are collected from 3D spacenav mouse. I've created the method `generate_trajectory()` within the main.py in the folder `main` in `master` branch. I'm pretty sure that the code would not work from the scratch since it requires the installation of the 3D spacenav libraries but give it a try.

**Comment by Lygggggg** [comment]
Yes, I have seen this part of the code in the master branch, and installed
spacenav-related driver files. What you mean is that you can use the mouse
to control the motion of the robotic arm in the simulation environment to
obtain expert trajectory data? I haven't figured out how the
generate_trajectory() function works yet. In addition, when I try to get
the expert demo data of the reaching task, it seems to be messing around.

Jeonghoon Lee ***@***.***> 于2021年11月30日周二 下午2:25写道：

**Comment by Lygggggg** [comment]
> Those trajectories are collected from 3D spacenav mouse. I've created the method `generate_traj()` within the `main.py` in the folder `main` in `master` branch. I'm pretty sure that the code would not work from the scratch since it requires the installation of the 3D spacenav libraries but give it a try. FYI, I used the pyspacenav package from https://github.com/mastersign/pyspacenav

I think I may understand what you mean. 3D Mouse is a hardware device, is it possible to control the motion of the robotic arm in simulation through this device?

**Comment by TMmichi** [comment]
> I think I may understand what you mean. 3D Mouse is a hardware device, is it possible to control the motion of the robotic arm in simulation through this device?

Exactly. If you look closely within the `generate_expert_traj` from `stable_baselines.gail`, you'll figure out how it works. Just to let you know, `_expert_3d` is the one that produces an action list from received signals from the spacenav.

**Comment by Lygggggg** [comment]
> > I think I may understand what you mean. 3D Mouse is a hardware device, is it possible to control the motion of the robotic arm in simulation through this device?
> 
> Exactly. If you look closely within the `generate_expert_traj` from `stable_baselines.gail`, you'll figure out how it works. Just to let you know, `_expert_3d` is the one that produces an action list from received signals from the spacenav.

Okay, thank you. I think I understand. I have no way to get expert trajectory data for the time being, because I can’t know the exact action list.

**Comment by Lygggggg** [comment]
> > I think I may understand what you mean. 3D Mouse is a hardware device, is it possible to control the motion of the robotic arm in simulation through this device?
> 
> Exactly. If you look closely within the `generate_expert_traj` from `stable_baselines.gail`, you'll figure out how it works. Just to let you know, `_expert_3d` is the one that produces an action list from received signals from the spacenav.

But I would like to ask, is there any way I can get the expert track data I want?

**Comment by TMmichi** [comment]
How would you like your trajectories to be? If you do have a spacenav, then the process gets fairly simple. 
1. event = spacenav.poll() within `_expert_3d` receives the command you gave via spacenav and store it into a MotionEvent class.
2. action = np.array([event.x, event.z, event.y, event.rx, -event.ry, event.rz]) creates an action list from the MotionEvent.
Action from step 2 can be thought of as the action from the policy. If you plug that action into the env.step, then the environment will give you the next state. If you also have a GUI on, then you would know what's going on.

**Comment by Lygggggg** [comment]
> How would you like your trajectories to be? If you do have a spacenav, then the process gets fairly simple.
> 
> 1. event = spacenav.poll() within `_expert_3d` receives the command you gave via spacenav and store it into a MotionEvent class.
> 2. action = np.array([event.x, event.z, event.y, event.rx, -event.ry, event.rz]) creates an action list from the MotionEvent.
> 
> Action from step 2 can be thought of as the action from the policy. If you plug that action into the env.step, then the environment will give you the next state. If you also have a GUI on, then you would know what's going on. You simply need to record those states, actions, and next states.

The sad thing is that I don't have such a device at the moment, so I may need to find another way to get the expert trajectory data I expect.

**Comment by TMmichi** [comment]
> > How would you like your trajectories to be? If you do have a spacenav, then the process gets fairly simple.
> > 
> > 1. event = spacenav.poll() within `_expert_3d` receives the command you gave via spacenav and store it into a MotionEvent class.
> > 2. action = np.array([event.x, event.z, event.y, event.rx, -event.ry, event.rz]) creates an action list from the MotionEvent.
> > 
> > Action from step 2 can be thought of as the action from the policy. If you plug that action into the env.step, then the environment will give you the next state. If you also have a GUI on, then you would know what's going on. You simply need to record those states, actions, and next states.
> 
> The sad thing is that I don't have such a device at the moment, so I may need to find another way to get the expert trajectory data I expect.

If you don't have a spacenav, then that's fine. You can just create any method that receives your command (literally any method: it can be keyboard inputs from the `keyboard` package, or ROS keyboard input node, or even python internal input function) and toss it to the `generate_expert_traj`. Make sure your method receives the state as an input and outputs an action.

**Comment by Lygggggg** [comment]
> > > How would you like your trajectories to be? If you do have a spacenav, then the process gets fairly simple.
> > > 
> > > 1. event = spacenav.poll() within `_expert_3d` receives the command you gave via spacenav and store it into a MotionEvent class.
> > > 2. action = np.array([event.x, event.z, event.y, event.rx, -event.ry, event.rz]) creates an action list from the MotionEvent.
> > > 
> > > Action from step 2 can be thought of as the action from the policy. If you plug that action into the env.step, then the environment will give you the next state. If you also have a GUI on, then you would know what's going on. You simply need to record those states, actions, and next states.
> > 
> > 
> > The sad thing is that I don't have such a device at the moment, so I may need to find another way to get the expert trajectory data I expect.
> 
> If you don't have a spacenav, then that's fine. You can just create any method that receives your command (literally any method: it can be keyboard inputs from the `keyboard` package, or ROS keyboard input node, or even python internal input function) and toss it to the `generate_expert_traj`. Make sure your method receives the state as an input and outputs an action.

Okay,thank you very much,i will try it.
